# Milestone 8
linux:
  hosts:
  children:    
    ubuntu:
      hosts:
        10.0.5.29:
          hostname: ubuntu
        10.0.5.30:
          hostname: ubuntu-1
      vars:
        device: ens192

  vars:
    public_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDbPcDEhznGHKcNd2QeGQmICz4Y+w0+VvjSYHbBhoQt6CxiVOnUrbKKK7+whhSUAb5JQa2W7+4CSdbI/4O8oMU8Y4Z4YrGV+gynJuPDtK1MtyKOuNwCGSlrE/WrSq3LWiJmw2YJvBVUCen+5Nll5S8/SG9U+WFi2d4tkWU+k5iIybqusnz44RkF19RxCHSV483Ka86d2Bh2kRhdVqQx8RolBIgb0jxxGaKzNhxh/ea4sAQ2s5thlHDTzMoe3XXMRQXeeTo92HwhXw35Fsj3Xwj3eK4y+BkIZbSKIh35VWnxwSgnneTzI68MllI1fBsRtkCn5HeWVje2ATqtSCsJ2U6CRRMzJdP12K8G3Tt7ycB0ABstlDfP55vijqdwoBm1bTOoSbkG8Ls+EJXIiJkGTn3huSQVnqxowGK08glCEELz6aJpwbm1JvFv7evbz2Kak7+BGayj6aFhkuuj4AYk6AF6N3c/wTpvDaW6l/Y0bYhHBNNtPptR0ZBKTNXPZFR6AEU= user3@xubuntu-wan"
    ansible_user: rangeuser
    prefix: 24
    gateway: 10.0.5.2
    name_server: 10.0.5.5
    domain: blue1.local
    